In [10]:
import numpy as np
import scipy.optimize as spopt
import re

In [12]:
cpu_regex = re.compile(r"^RESULT-cpu: (.*)$")
eqns_regex = re.compile(r"^eqns: (.*)$")

In [17]:
times = []
eqns = []
with open("results.dat",'r') as f:
    for l in f:
        cpu_match = cpu_regex.match(l)
        eqns_match = eqns_regex.match(l)
        if cpu_match:
            times.append(float(cpu_match.group(1)))
        elif eqns_regex.match(l):
            eqns.append(np.array([float(item) for item in eqns_match.group(1).split(",")]))
            
eqns

[array([  1.75950000e+04,   1.87856653e+09,   3.14279823e+08,
          2.90307262e+08,   2.55828252e+09,   1.59433960e+09]),
 array([  1.75950000e+04,   1.87856653e+09,   3.14279823e+08,
          2.90307262e+08,   2.55828252e+09,   1.59433960e+09]),
 array([  1.75950000e+04,   1.87856653e+09,   3.14279823e+08,
          2.90307262e+08,   2.55828252e+09,   1.59433960e+09]),
 array([  5.54998975e+08,   9.44998750e+09,   2.74499614e+09,
          1.43999735e+09,   5.02499310e+09,   4.61999366e+09]),
 array([  5.54998975e+08,   9.44998750e+09,   2.74499614e+09,
          1.43999735e+09,   5.02499310e+09,   4.61999366e+09]),
 array([  5.54998975e+08,   9.44998750e+09,   2.74499614e+09,
          1.43999735e+09,   5.02499310e+09,   4.61999366e+09]),
 array([  2.12952851e+08,   1.02661906e+09,   1.99918020e+08,
          4.15681742e+08,   1.34635838e+09,   1.23688677e+09]),
 array([  2.12952851e+08,   1.02661906e+09,   1.99918020e+08,
          4.15681742e+08,   1.34635838e+09,   1.23688677