In [3]:
import numpy as np
import scipy.optimize as spopt
import re

In [4]:
cpu_regex = re.compile(r"^RESULT-cpu: (.*)$")
eqns_regex = re.compile(r"^eqns: (.*)$")

In [32]:
times = []
eqns = []
with open("results.dat",'r') as f:
    for l in f:
        cpu_match = cpu_regex.match(l)
        eqns_match = eqns_regex.match(l)
        if cpu_match:
            times.append(float(cpu_match.group(1)))
        elif eqns_regex.match(l):
            eqns.append(np.array([float(item) for item in eqns_match.group(1).split(",")]))
        
eq_arr = np.array(eqns)
time_arr = np.array(times)
eq_arr.shape
#time_arr.shape
time_arr


array([  1059310.,   1073664.,   1056405.,   5581522.,   5477139.,
         5478820.,   2703046.,   2709509.,   2661789.,   4941879.,
         4948946.,   4967496.,   5475094.,   5533312.,   5453804.,
         3412978.,   3225581.,   3223278.,   1051571.,   1054508.,
         1051151.,   4282429.,   4266057.,   4188156.,   4305697.,
         4311935.,   4305486.,   3635246.,   3623923.,   3689039.,
         1275067.,   1258049.,   1274537.,   4131770.,   4182068.,
         4110768.,   1147066.,   1146418.,   1123650.,   6871261.,
         6839774.,   6838941.,   2221798.,   2248347.,   2226689.,
         4174103.,   4175047.,   4174018.,   3896003.,   3713441.,
         3768789.,  21797041.,  21614840.,  21738040.,  12308998.,
        12262418.,  12261372.,   2795317.,   2775756.,   2833213.,
          913117.,    938958.,    918944.,   1152332.,   1327514.,
         1141944.,   2847309.,   2836380.,   2831153.,   1255886.,
         1255963.,   1255927.,  21619867.,  21174627.,  218278

In [30]:
spopt.nnls(eq_arr, np.transpose(time_arr))

(array([ 0.        ,  0.00029613,  0.        ,  0.00032465,  0.00034146,  0.        ]),
 57722069.99237152)

In [31]:
spopt.nnls(np.delete(eq_arr, 5, 1), np.transpose(time_arr))

(array([ 0.        ,  0.00029613,  0.        ,  0.00032465,  0.00034146]),
 57722069.99237152)