In [5]:
import numpy as np
import scipy.optimize as spopt
import re
from random import randint

In [6]:
cpu_regex = re.compile(r"^RESULT-cpu: (.*)$")
eqns_regex = re.compile(r"^eqns: (.*)$")

In [11]:
times = []
eqns = []
with open("results_gpg.dat",'r') as f:
    for l in f:
        cpu_match = cpu_regex.match(l)
        eqns_match = eqns_regex.match(l)
        if cpu_match:
            times.append(float(cpu_match.group(1)))
        elif eqns_regex.match(l):
            eqns.append(np.array([float(item) for item in eqns_match.group(1).split(",")]))
        
eq_arr = np.array(eqns)
time_arr = np.array(times)
eq_arr.shape
#time_arr.shape
time_arr.size
#eq_arr.size

84

In [12]:
spopt.nnls(eq_arr, np.transpose(time_arr))

(array([ 0.00019148,  0.00045556,  0.        ,  0.00055118,  0.0002794 ,  0.        ]),
 70202293.69243)

In [13]:
spopt.nnls(np.delete(eq_arr, 5, 1), np.transpose(time_arr))

(array([ 0.00019148,  0.00045556,  0.        ,  0.00055118,  0.0002794 ]),
 70202293.69243)

In [20]:
rarr = [randint(0,time_arr.size -1) for _ in range(40)]
rarr

[11,
 52,
 65,
 17,
 58,
 24,
 21,
 24,
 38,
 0,
 27,
 25,
 27,
 81,
 78,
 64,
 50,
 67,
 73,
 1,
 4,
 5,
 56,
 6,
 35,
 16,
 50,
 65,
 79,
 5,
 55,
 66,
 23,
 20,
 28,
 0,
 68,
 83,
 60,
 26]

In [21]:
subset_e  = np.delete(eq_arr, rarr, 0)
subset_times = np.delete(time_arr, rarr, 0)

spopt.nnls(np.delete(subset_e, 5, 1), np.transpose(subset_times))

(array([  2.36054760e-03,   5.56974616e-04,   2.36252221e-04,
          7.44498620e-05,   1.44651958e-04]), 60949144.22250348)