In [1]:
import numpy as np
import scipy.optimize as spopt
import re
from random import randint

In [2]:
cpu_regex = re.compile(r"^RESULT-cpu: (.*)$")
eqns_regex = re.compile(r"^eqns: (.*)$")

In [3]:
times = []
eqns = []
with open("results.dat",'r') as f:
    for l in f:
        cpu_match = cpu_regex.match(l)
        eqns_match = eqns_regex.match(l)
        if cpu_match:
            times.append(float(cpu_match.group(1)))
        elif eqns_regex.match(l):
            eqns.append(np.array([float(item) for item in eqns_match.group(1).split(",")]))
        
eq_arr = np.array(eqns)
time_arr = np.array(times)
eq_arr.shape
#time_arr.shape
time_arr.size
eq_arr.size

486

In [4]:
spopt.nnls(eq_arr, np.transpose(time_arr))

(array([ 0.        ,  0.00029613,  0.        ,  0.00032465,  0.00034146,  0.        ]),
 57722069.99237152)

In [6]:
spopt.nnls(np.delete(eq_arr, 5, 1), np.transpose(time_arr))

(array([ 0.        ,  0.00029613,  0.        ,  0.00032465,  0.00034146]),
 57722069.99237152)

In [5]:
rarr = [randint(0,time_arr.size -1) for _ in range(40)]
rarr

[23,
 15,
 53,
 50,
 60,
 0,
 56,
 17,
 40,
 52,
 57,
 47,
 59,
 75,
 78,
 23,
 71,
 65,
 13,
 74,
 6,
 30,
 78,
 65,
 0,
 65,
 64,
 28,
 47,
 57,
 44,
 47,
 22,
 78,
 43,
 2,
 36,
 48,
 30,
 6]

In [8]:
subset_e  = np.delete(eq_arr, rarr, 0)
subset_times = np.delete(time_arr, rarr, 0)

spopt.nnls(np.delete(subset_e, 5, 1), np.transpose(subset_times))

(array([ 0.        ,  0.00029873,  0.0001574 ,  0.00041218,  0.00029189]),
 41787111.2273011)